### ISSUE TITLE
Compilation fails on osx catalina xcode 12.0.1

### ISSUE THREAD

**Issue by silviucpp** [ninenines/nif_helpers#2]
nif_helpers.c:175:2: error: implicit declaration of function 'erl_drv_steal_main_thread' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        erl_drv_steal_main_thread(name, &(st->tid), nif_main_thread, st, NULL);
        ^
1 error generated.

**Comment by essen** [comment]
I do not have access to this environment. Patch welcome!

**Comment by silviucpp** [comment]
I think only fix is using -Wno-implicit-function-declaration in CFLAGS

**Comment by silviucpp** [comment]
Will make some tests. maybe adding the function declaration using external might be a better solution. using "-Wno-implicit-function-declaration" might hide other functions as well

**Comment by fabjan** [comment]
`nif_helpers.c` seems to be calling [a private function in beam] when built for macOS.

I'd be happy to work on and test some fix, I have access to this environment, but not sure how to approach a fix. C is not something I hack much at all. There is not header file for beam which declares it, so it doesn't appear to be meant to be used.

A crappy way to get rid of the warning is to put a declaration of the function before `erl_drv_steal_main_thread` is called and that seems to be as (if not more) robust as compiling it with that warning disabled, since it will only affect that one function instead of all of them.

[a private function in beam]: https://github.com/erlang/otp/blob/40922798411c2d23ee8a99456f96d6637c62b762/erts/emulator/beam/erl_drv_thread.c#L733

**Comment by essen** [comment]
I have a Catalina now (not using xcode though) but I don't think I've seen this error. I'll check next week. cc @lhoguin

**Comment by eskil** [comment]
Here's a patch that will make it compile on Darwin. A better patch might be to expose the relevant functions and structures in a header file.

https://github.com/eskil/nif_helpers/commit/6bcdf5646fa1078623a7dbd3ccb21846a64dff39

I'll make a pull request in case you want to apply this.

**Comment by essen** [comment]
How do you get compilation to fail? Could you share quick steps to reproduce?

**Comment by eskil** [comment]
Sure thing! 

I check out ninenines/esdl2 and try and build that. It depends on nif_helpers and runs into the compilation error;

```
$ git clone git@github.com:ninenines/esdl2.git
$ cd esdl2
$ make
erlang.mk:26: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
 DEP    nif_helpers (master)
...
C      nif_helpers.c
/Users/eskil/src/github/ninenines/esdl2/deps/nif_helpers/nif_helpers.c:175:2: error: implicit declaration of function 'erl_drv_steal_main_thread' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        erl_drv_steal_main_thread(name, &(st->tid), nif_main_thread, st, NULL);
        ^
```

I forked esdl2 and nif_helpers, and point esdl2 to the patched nif_helpers. Compilation succeeds and esdl2 works.

The full `uname -a` output for me is

```
Darwin Eskil.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```

**Comment by essen** [comment]
I don't see it because I have since upgraded to Monterey and there's no problem there.

I wonder however if it still is a problem if, in esdl2, you do a `make erlang-mk` first? There's been Darwin fixes since.

**Comment by eskil** [comment]
No, same problem. I'm on Ventura which is a successor to Monterey. Same error.

```
10:36:00  eskil@eskil-C02ZF0GKLVDL ~/src/github/ninenines$ git clone git@github.com:ninenines/esdl2.git
Cloning into 'esdl2'...
remote: Enumerating objects: 1392, done.
remote: Total 1392 (delta 0), reused 0 (delta 0), pack-reused 1392
Receiving objects: 100% (1392/1392), 725.02 KiB | 2.02 MiB/s, done.
Resolving deltas: 100% (1044/1044), done.
10:36:06  eskil@eskil-C02ZF0GKLVDL ~/src/github/ninenines$ cd esdl2/
10:36:08  eskil@eskil-C02ZF0GKLVDL ~/src/github/ninenines/esdl2 (master)$ make erlang.mk
erlang.mk:26: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
 DEP    nif_helpers (master)
erlang.mk:26: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
make: Nothing to be done for `erlang.mk'.
10:36:15  eskil@eskil-C02ZF0GKLVDL ~/src/github/ninenines/esdl2 (master)$ make
erlang.mk:26: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
make[1]: Nothing to be done for `all'.
 DEPEND esdl2.d
 C      esdl2.c
 C      esdl2_cursors.c
 C      esdl2_renderers.c
 C      esdl2_windows.c
 C      internal.c
 C      sdl.c
 C      sdl_blend_mode.c
 C      sdl_clipboard.c
 C      sdl_cpu_info.c
 C      sdl_cursor.c
 C      sdl_events.c
 C      sdl_filesystem.c
 C      sdl_gl.c
 C      sdl_hints.c
 C      sdl_keyboard.c
 C      sdl_keycode.c
 C      sdl_mouse.c
 C      sdl_pixels.c
 C      sdl_platform.c
 C      sdl_power.c
 C      sdl_rect.c
 C      sdl_renderer.c
 C      sdl_stdinc.c
 C      sdl_surface.c
 C      sdl_texture.c
 C      sdl_ttf.c
 C      sdl_version.c
 C      sdl_video.c
 C      sdl_window.c
 C      nif_helpers.c
/Users/eskil/src/github/ninenines/esdl2/deps/nif_helpers/nif_helpers.c:175:2: error: implicit declaration of function 'erl_drv_steal_main_thread' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        erl_drv_steal_main_thread(name, &(st->tid), nif_main_thread, st, NULL);
        ^
1 error generated.
make: *** [/Users/eskil/src/github/ninenines/esdl2/deps/nif_helpers/nif_helpers.o] Error 1
```

**Comment by fabjan** [comment]
I don't remember how I found this issue on GitHub a year ago, but I still see this issue (I'm now on Big Sur on this machine):

```
❯ uname -a
Darwin mbair2019.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 29 04:31:06 PDT 2022; root:xnu-7195.141.39~2/RELEASE_X86_64 x86_64
```

Since this discussion woke up again, I tried to clone and compile esdl2 and get the same error as above. Same if I do `make erlang.mk` first.

If I add the following ugly hack to `deps/nif_helpers/nif_helpers.h` (right after `#include "erl_nif.h"
`):

```
// Forward declarations of some internal Erlang stuff.
typedef pthread_t ethr_tid;
typedef unsigned int Uint;
struct ErlDrvTid_ {
    ethr_tid tid;
    void* (*func)(void*);
    void* arg;
    int drv_thr;
    Uint tsd_len;
    void **tsd;
    char *name;
};
typedef struct ErlDrvTid_ *ErlDrvTid;
int erl_drv_steal_main_thread(char *name,
                              ErlDrvTid *dtid,
                              void* (*func)(void*),
                              void* arg,
                              ErlDrvThreadOpts *opts);
```

It compiles without complaining.

I found them by grepping the OTP source:

```
❯ rg 'int erl_drv_steal_main_thread' ~/code/otp 
/Users/fabian/code/otp/erts/emulator/beam/erl_drv_thread.c
733:int erl_drv_steal_main_thread(char *name,

/Users/fabian/code/otp/lib/wx/c_src/wxe_main.cpp
41:  int erl_drv_steal_main_thread(char *name,

❯ rg 'typedef .*ErlDrvTid;' ~/code/otp        
/Users/fabian/code/otp/erts/emulator/beam/erl_driver.h
200:typedef struct ErlDrvTid_ *ErlDrvTid;

❯ rg 'struct ErlDrvTid_ \{' ~/code/otp         
/Users/fabian/code/otp/erts/emulator/beam/erl_drv_thread.c
79:struct ErlDrvTid_ {

❯ rg 'typedef .* ethr_tid;' ~/code/otp    
/Users/fabian/code/otp/erts/include/internal/ethread.h
130:typedef pthread_t ethr_tid;

❯ rg 'typedef .* Uint;' ~/code/otp        
/Users/fabian/code/otp/lib/erl_interface/src/decode/decode_big.c
97:typedef unsigned int Uint;

```

As I wrote above, I'm not used to working with things like this in C, so I don't know the "idiomatic" way of declaring functions there are no provided header files for. It seems like that would be a rather brittle solution.

It also works if you just add:

```
int erl_drv_steal_main_thread(char *name,
                              ErlNifTid *dtid,
                              void* (*func)(void*),
                              void* arg,
                              ErlDrvThreadOpts *opts);
```

because ErlNifTid and ErlDrvTid are both typedefed from ErlDrvTid_, and ErlNifTid is defined in the public erl_nif.h header file included by nif_helpers.h.

Not sure if any of this helps, just sharing the notes from my experiments now that the discussion woke up in this issue.

And by "works" I mean it compiles.

**Comment by silviucpp** [comment]
To bypass this problem on my side instead using `-Wno-implicit-function-declaration` which might hide other functions I don't want  I prefer to specify them independently like: `LDFLAGS +=  -Wl,-U,_enif_is_binary`

**Comment by essen** [comment]
OK I probably don't have the same compiler, I'll try again tomorrow. What's your `cc --version`?

**Comment by silviucpp** [comment]
On my side is:

```
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Not the last one, but I can replicate this on all versions I tried in the last 2 years.

**Comment by eskil** [comment]
I have 
```
$ cc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I think declaring the definitions (as fabian suggested) is a better fix than disabling a warning.

**Comment by essen** [comment]
https://github.com/ninenines/nif_helpers/commit/d1147e0d19df4b9ff332160ef03fd1335b22337d should fix it. Thanks everyone!

**Comment by eskil** [comment]
Confirmed, works now.
